### ISSUE TITLE
"Bystander" card doesn't provide interaction feedback for Agents

### ISSUE THREAD

**Issue by TassSinclair** [kksy/codenames-portable#1]
## Story
AS AN Agent, I WANT TO know when I have chosen a bystander card SO I CAN know that I have picked an incorrect card.

## Current behaviour
GIVEN I am an Agent
WHEN I click a Bystander card
THEN the Spymaster's view changes the colour of the card that was clicked to a Bystander colour

## Expected behaviour
GIVEN I am an Agent
WHEN I click a Bystander card
THEN the Agent's view changes the colour of the card that was clicked to a Bystander colour
AND the Spymaster's view changes the colour of the card that was clicked to a Bystander colour

**Comment by kksy** [comment]
Now using grey for untouched  cards so the bystander cards can turn yellow
https://github.com/kksy/codenames-portable/commit/1053c68830c42f31f12c44a626db5fd6bfc65a65
